spring:
  application:
    name: mssproject
  datasource:
    url: jdbc:h2:mem:mssproject;DB_CLOSE_DELAY=-1
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: off
    properties:
      hibernate:
        format_sql: false
        default_batch_fetch_size: 1000
    database-platform: org.hibernate.dialect.H2Dialect